import './globals.css'

import { Inter } from 'next/font/google'
import Main from "../components/Main/Main"

// @import url("./component.styles.css");
import "./component.styles.css"

import { cookies } from 'next/headers'
const inter = Inter({ subsets: ['latin'] })

export const metadata= {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  const cookiesList = cookies()
  const hasCookie = cookiesList.has('theme')

  if(hasCookie){
    const theme = cookiesList.get('theme')
    if(theme === 'dark'){
      inter.className = 'rad-ui-dark-theme'
    }
  }

  // console.log(cookiesList,hasCookie)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main>
            {children}
        </Main>
      </body>
    </html>
  )
}
